### ISSUE TITLE
Trying the start.sh it's failed on Step 2.

### ISSUE THREAD

**Issue by Olichous** [cisco-ie/tdm#91]
root@nettools:/home/nettools/TDM/tdm# ./start.sh 
Building etl
Sending build context to Docker daemon  92.67kB
Step 1/10 : FROM python:3-alpine
 ---> 27edb73bd1fc
Step 2/10 : RUN pip install --no-cache-dir pip==18.0
 ---> Running in 7dee32f7bdf9
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff0be37c8e0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff0be37e920>: Failed to establish a new connection: [Errno -3] Try again')': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff0be37cc10>: Failed to establish a new connection: [Errno -3] Try again')': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff0be37de70>: Failed to establish a new connection: [Errno -3] Try again')': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff0be37c790>: Failed to establish a new connection: [Errno -3] Try again')': /simple/pip/
ERROR: Could not find a version that satisfies the requirement pip==18.0 (from versions: none)
ERROR: No matching distribution found for pip==18.0
The command '/bin/sh -c pip install --no-cache-dir pip==18.0' returned a non-zero code: 1
ERROR: Service 'etl' failed to build : Build failed
root@nettools:/home/nettools/TDM/tdm#

**Comment by Olichous** [comment]
You can close the case -> proxy issue.
Now it's :
Step 4/10 : RUN pip install pipenv
 ---> Running in 66e014f4de87
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal import main
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/index.py", line 14, in <module>
    from pip._vendor import html5lib, requests, six
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/html5lib/__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/html5lib/html5parser.py", line 8, in <module>
    from . import _tokenizer
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/html5lib/_tokenizer.py", line 16, in <module>
    from ._trie import Trie
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/html5lib/_trie/__init__.py", line 3, in <module>
    from .py import Trie as PyTrie
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/html5lib/_trie/py.py", line 6, in <module>
    from ._base import Trie as ABCTrie
  File "/usr/local/lib/python3.10/site-packages/pip/_vendor/html5lib/_trie/_base.py", line 3, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
The command '/bin/sh -c pip install pipenv' returned a non-zero code: 1
ERROR: Service 'etl' failed to build : Build failed

**Comment by Olichous** [comment]
Ok foud the issue
